In [113]:
import pandas as pd
import numpy as np

In [114]:
A = np.array([1,2,3])

A

array([1, 2, 3])

In [115]:
B = np.array([[4.0,5.9,6.7],[1.2,3.4,7.0]])

B

array([[4. , 5.9, 6.7],
       [1.2, 3.4, 7. ]])

In [116]:
A.shape

(3,)

In [117]:
A.ndim

1

In [118]:
B.ndim

2

In [119]:
B.shape

(2, 3)

In [120]:
type(A)

numpy.ndarray

In [121]:
A.dtype

dtype('int64')

In [122]:
type(B)

numpy.ndarray

In [123]:
B.dtype

dtype('float64')

In [124]:
A.itemsize

8

In [125]:
A.nbytes

24

In [126]:
B.itemsize

8

In [127]:
B.nbytes

48

In [128]:
A = np.array([[1,3,4,5,6,7],[8,9,0,2,34,67]])

In [129]:
A

array([[ 1,  3,  4,  5,  6,  7],
       [ 8,  9,  0,  2, 34, 67]])

In [130]:
A[1,3]

2

In [131]:
A[0]

array([1, 3, 4, 5, 6, 7])

In [132]:
A[:,3]

array([5, 2])

In [133]:
A[0,1:5:2]

array([3, 5])

In [134]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [135]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [136]:
np.ones((4,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [137]:
np.full((2,2),89)

array([[89, 89],
       [89, 89]])

In [138]:
np.random.rand(2,3)

array([[0.82560624, 0.08916614, 0.65801564],
       [0.54941658, 0.63507977, 0.96907957]])

In [139]:
np.random.random_sample(A.shape)

array([[0.53531251, 0.00329914, 0.13989855, 0.04435635, 0.3477246 ,
        0.2201065 ],
       [0.46822456, 0.73651536, 0.93597185, 0.68490987, 0.09802573,
        0.60343486]])

In [140]:
np.random.randint(1,4,size=(3,3))

array([[1, 3, 1],
       [3, 2, 1],
       [1, 2, 2]])

In [141]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [142]:
arr = np.array([[1,2],[3,4]])
r1 = np.repeat(arr,3,axis=1)

r1

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [143]:
a = np.array([1,2,4])
b = a

b

array([1, 2, 4])

In [144]:
b[1] = 5

b

array([1, 5, 4])

In [145]:
a

array([1, 5, 4])

In [146]:
a = np.array([1,2,4])

In [147]:
a+2

array([3, 4, 6])

In [148]:
a-3

array([-2, -1,  1])

In [149]:
a*2

array([2, 4, 8])

In [150]:
a/2

array([0.5, 1. , 2. ])

In [151]:
b = np.array([3,4,5])

In [152]:
a+b

array([4, 6, 9])

In [153]:
a ** 2

array([ 1,  4, 16])

In [154]:
np.sin(a)

array([ 0.84147098,  0.90929743, -0.7568025 ])

In [155]:
a = np.ones((2,3))

a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [156]:
b = np.full((3,2),2)

b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [157]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [158]:
np.dot(a,b)

array([[6., 6.],
       [6., 6.]])

In [159]:
c = np.identity(3)

np.linalg.det(c)

1.0

In [160]:
np.linalg.inv(c)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [161]:
np.linalg.eigvals(c)

array([1., 1., 1.])

In [162]:
np.linalg.eigvalsh(c)

array([1., 1., 1.])

In [163]:
stats = np.array([[1,2,3],[4,5,6]])

stats

array([[1, 2, 3],
       [4, 5, 6]])

In [164]:
np.min(stats)

1

In [165]:
np.max(stats)

6

In [166]:
np.sum(stats)

21

In [167]:
np.mean(stats)

3.5

In [168]:
after = stats.reshape(3,2)

after

array([[1, 2],
       [3, 4],
       [5, 6]])

In [169]:
temp = stats.reshape(6,1)

temp

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [170]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [175]:
h1 = np.ones((2,3))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])